export { default as Navbar } from './Navbar/Navbar';
export { default as HompageCarousel } from './Hompage-carousel/Hompage-carousel';
export { default as OurInfo } from './OurInfo/OurInfo';
export { default as OurTopService } from './OurTopServices/OurTopServices';
export { default as Footer } from './Footer/Footer';
export { default as contactUs } from './ContactUs/ContactUs';
export { default as OurServices } from './Services/Services';
export { default as NoResults} from './NoResults/NoResults';
export { default as UnderConstruction } from './UnderConstruction/UnderConstruction';
export { default as TermsandConditions } from './TermsandConditions/TermsandConditions';
export { default as PrivacyAndCookierPolicy } from './PrivacyAndCookiePolicy/PrivacyAndCookiePolicy';
export { default  as Loading } from './Loading/Loading';
export { default as Marquee } from './Marquee/Marquee';
export { default as SearchBarJobsHub } from './JobsHub/SearchBar';
export { default as JobsHubPagination } from './JobsHub/JobsHubPagination';